
title: "Course on SAR-PolSAR Statistics"
author: "Alejandro C. Frery and Antonio C. Medeiros"
date: "Initial: 11 June 2017"
output:
  html_document: default
  html_notebook: default


Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).

# Parte I: Elementos de analisis estadistico de imagenes PolSAR usando R

## A1 -- Formacion del dato SAR

## A2 -- El modelo multiplicativo y distribuciones de intensidad

El specke se forma por la suma coherente (con registro de la fase) del retorno de cada elemento (retrodispersor) en la célula de resolución de la imagen.

El retorno en cada pixel es un número complejo:
$$
A = \sum_{j=1}^N A_j e^{i \phi_j}.
$$
Así, el retorno tiene partes real e imaginaria $\Re(A)=\sum_{j=1}^N A_j \cos{i \phi_j}$ y $\Im(A)=\sum_{j=1}^N A_j \sin{i \phi_j}$, respectivamente.

Suponiendo que hay una gran cantidad de elementos en la célula de resolución ($N\to\infty$), y que ninguno predomina sobre los otros, podemos aplicar el Teorema Central del Límite y afirmar que el par $(\Re(A),\Im(A))$ es formado por variables aleatorias gaussianas independientes e idénticamente distribuídas de media nula, y la fase $\angle(\Re(A),\Im(A))$ obedece una distribución uniforme en $[-\pi,\pi]$.

```{r}
if(!require(shape)){install.packages("shape"); require("shape")}
if(!require(wesanderson)){install.packages("wesanderson"); require("wesanderson")}

set.seed(1234567890, kind="Mersenne-Twister")
factor.reduccion <- .5

### Gráfico de formación del speckle

N <- 10 # número de retrodispersores
sigma2 <- 1
RAi <- c(0, rnorm(n = N, mean = 0, sd = sqrt(sigma2)))
IAi <- c(0, rnorm(n = N, mean = 0, sd = sqrt(sigma2)))

### Determinación de la caja para dibujar los ejes
rangex <- range(cumsum(RAi))
rangey <- range(cumsum(IAi))
maxaxis <- max(abs(c(rangex, rangey))) * factor.reduccion

### El área de dibujo
plot(c(-maxaxis, maxaxis), c(-maxaxis, maxaxis), type = "n", asp = 1,
     axes = FALSE,
     xlab = "Componentes Reales", ylab = "Componentes Imaginarias")
Arrows(x0 = -maxaxis, y0 = 0, x1 = maxaxis, y1 = 0, arr.type="triangle")
Arrows(y0 = -maxaxis, x0 = 0, y1 = maxaxis, x1 = 0, arr.type="triangle")

### Los vectores sumándose
Arrows(x0 = RAi[1:(N)], y0 = IAi[1:(N)], x1 = RAi[2:(N+1)], y1 = IAi[2:(N+1)], lwd=.3)

### El vector final
Arrows(x0 = 0, y0 = 0, x1 = RAi[N+1], y1 = IAi[N+1], lwd = 3, col = 2)

### Fin Gráfico de formación del speckle
```

## T1 -- Introducción


### Nociones de programación en R


## T2 -- Lectura de datos

## T3 -- Operaciones basicas en R

## T4 -- Visualizacion de imagenes, mejoria de contraste

## T5 -- Analisis estadistico descriptivo 

## T6 -- Analisis estadistico cuantitativo

## A3 -- Filtros reductores de speckle

## A4 -- Evaluacion de filtros

# Parte II: PolSARpro

## T7 -- Introduccion

## T8 -- Lectura de datos

## A5 -- Datos polarimetricos: distribuciones 

## A6 -- Descomposicion H-alfa

## A7 -- Clasificacion

## T9 -- Operaciones en PolSARpro: filtrado de speckle, descomposiciones polarimetricas, clasificacion

## T10 -- Exportacion

## A8 -- Tests de hipotesis y deteccion de cambios