---
title: ''
output:
  pdf_document: default
  html_notebook: default
  html_document: default
---


Nome: Antonio C. Medeiros  
Meteorologista  
Gerente de projetos  
Laboratório de Computação Cientifíca e Analise Númerica - LaCCAN  
  
E-mail:antoniomedeiros@laccan.ufal.br / medeiros.tonny@gmail.com  
Contato: +55 82 98814-6163 (WhatsApp)  
  
O curso será dividido:  
R statistic  
  
T1.  Introducción  
T2.  Lectura de datos  
T3.  Operaciones básicas en R  
T4.  Visualización de imágenes, mejoría de contraste  
T5.  Análisis estadístico descriptivo  
T6.  Análisis estadístico cuantitativo  
  
Parte II: PolSARpro  
  
T7.  Introducción  
T8.  Lectura de datos  
T9.  Operaciones en PolSARpro: filtrado de speckle, descomposiciones  
polarimétricas, clasificación  
T10. Exportación  
  
  
## T1 -- Introducción

R é um programa livre e um ambiente computacional de exploração de gráficos e
análise de dados (Chambers 6
, 2008). Ele é útil para qualquer pessoa que usa e interpreta
dados, das seguintes maneiras:

• Super-calculadora;  
• Ambiente com diversos pacotes estatísticos;  
• Ferramenta de gráficos de alta qualidade;  
• Linguagem de programação multi-uso.  

O R é utilizado para explorar, analisar e compreender os dados epidemiológicos. Os
dados podem ser importados de fontes como, por exemplo, o DATASUS 1 ou o IBGE 2
em planilhas de Excel.


### Como Instalar o R
O R é um software livre para computação estatística e construção de gráficos que pode ser baixado e distribuído
gratuitamente de acordo com a licença GNU.
O R está disponível para as plataformas UNIX, Windows e MacOS. 

O R é case-sensitive, isto é, ele diferencia letras maiúsculas de minúsculas, portanto A é diferente de a. O
separador de casas decimais é ponto ".". A vírgula é usada para separar argumentos (informações). Não é
recomendado o uso de acentos em palavras (qualquer nome que for salvar em um computador, não só no R,
evite usar acentos. Acentos são comandos usados em programação e podem causar erros, por exemplo, em
documentos do word e excel).

### Demonstrações
Algumas funções do R possuem demonstrações de uso. Estas demonstrações podem ser vistas
usando a função demo(). Vamos ver algumas demonstrações de gráficos que podem ser feitos no R. Digite
o seguinte na linha de comandos:  
> demo(graphics) # Vai aparecer uma mensagem pedindo que você tecle Enter para
prosseguir, depois clique na janela do gráfico para ir passando os exemplos.  

```{R}
demo(image)
```

      
> demo(image)

Agora vamos ver outros tipos.  

```{R}
demo(graphics)
```



### Pacotes do R
O R é um programa leve (ocupa pouco espaço e memória) e geralmente roda rápido, até em computadores
não muito bons. Isso porque ao instalarmos o R apenas as configurações mínimas para seu funcionamento
básico são instaladas (pacotes que vem na instalação “base”). Para realizar tarefas mais complicadas pode ser
necessário instalar pacotes adicionais (packages). 

### Como usar um pacote do R
Não basta apenas instalar um pacote. Para usá-lo é necessário "carregar" o pacote sempre que você abrir
o R e for usá-lo. Use a função library para rodar um pacote. Por exemplo: Digite library(vegan)
na linha de comandos do R.

library(vegan) # Após isso as funcionalidades do vegan estarão prontas para serem
usadas. Lembre-se que sempre que abrir o R será necessário carregar o pacote novamente.

### Como citar o R, ou um pacote do R em publicações
No R existe um comando que mostra como citar o R ou um de seus pacotes. Veja como fazer:

citation() # Mostra como citar o R
To cite R in publications use:
R Development Core Team (2011). R: A language and environment for statistical computing. R Foundation
for Statistical Computing, Vienna, Austria. ISBN 3-900051-07-0, URL http://www.R-project.org/.
Veja que na parte com o nome dos autores aparece "R development core team", isso está correto, cite o R
desta forma. Algumas pessoas não sabem disso e citam o R com autor Anônimo, isto tira o crédito do time.

Para citar um pacote, por exemplo o vegan, basta colocar o nome do pacote entre aspas.

citation("vegan")

### Ambiente de Desenvolvimetno Integrado IDE para R

##Objetivo

O objetivo do projeto Tinn-R é facilitar o aprendizado e o uso do potencial do ambiente estatístico e computacional R.

## Tinn-R
O Tinn-R é um editor/processador de texto ASCII/UNICODE genérico para o sistema operacional Windows, muito bem integrado ao ambiente estatístico e computacional R para o qual possui características de Interface Gráfica (GUI) e Ambiente de Desenvolvimento Integrado (IDE).

É um projeto registrado sob a Licença Pública Geral GPL, sendo portanto software livre.

## RStudio

RStudio é um ambiente de desenvolvimento integrado (IDE) para R. Ele inclui um console, editor de destaque de sintaxe que suporta a execução direta de código, bem como ferramentas para traçar, fazer histórico, depurar e gerenciar espaço de trabalho. 

O RStudio está disponível em edições comerciais e de código aberto e é executado na área de trabalho (Windows, Mac e Linux) ou em um navegador conectado ao RStudio Server ou RStudio Server Pro (Debian / Ubuntu, RedHat / CentOS e SUSE Linux).


R script é uma ambiente onde você pode adicionar uma nova janela dentro do seu ambiente Rstudio, facilitando assim a sua manupulação, diferente do R linha de comando.  

R notebook você cria um arquivo onde pode-se colocar incluso varias programas como códigos R, Latex, CC e outros, estamos utilizando esse modelo. Além de outro modos onde podemos abrir uma janela.  






